// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: ecode.proto

package ecode

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// CommonErrCode ecode
var (
	Success            = ecode.New(200)
	SendSmsErr         = ecode.New(50001)
	SendEmailErr       = ecode.New(50002)
	SmsCodeTimeOut     = ecode.New(50003)
	EmailCodeTimeOut   = ecode.New(50004)
	VerifySmsErr       = ecode.New(50005)
	VerifyEmailErr     = ecode.New(50006)
	InsertErr          = ecode.New(50007)
	FindErr            = ecode.New(50008)
	UpdateErr          = ecode.New(50009)
	DeleteErr          = ecode.New(50010)
	NoData             = ecode.New(50011)
	CreatTokenErr      = ecode.New(50012)
	VerifyTokenErr     = ecode.New(50013)
	VerifyRoleErr      = ecode.New(50014)
	GoogleVerifyErr    = ecode.New(50015)
	SystemMaintenance  = ecode.New(50016)
	NoLogin            = ecode.New(60000)
	LoginErr           = ecode.New(60001)
	TokenErr           = ecode.New(60002)
	NoUser             = ecode.New(60003)
	PhoneErr           = ecode.New(60004)
	PassWordErr        = ecode.New(60005)
	ArgsErr            = ecode.New(60006)
	RegisterCodeErr    = ecode.New(60007)
	UserAlreadyExists  = ecode.New(60008)
	CreatUserErr       = ecode.New(60009)
	CreatUserInviteErr = ecode.New(60010)
	UserDisabled       = ecode.New(60011)
	UserLogged         = ecode.New(60012)
	LogoutErr          = ecode.New(60013)
)
